Revise crytpo policy show usage
opensciencegrid/osg-system-profiler pull request #18
Opened 2023-04-18 18:34 UTC by jtakaki-matc

Add an if statement to check for version 8 or 9 because update-crypto-policies --show does not work with EL7

2023-05-26 21:53 UTC, matyasselmeci requested changes
Instead of explicitly checking /etc/os-release for the distro version, you should check the return code of `which update-crypto-policies &>/dev/null` to see if the script itself exists. (`&>XXX` is shorthand for `>XXX 2>&1`, i.e. redirecting both stdout and stderr).

The other thing: osg-system-profiler output is divided into sections. A section is a line that looks like
```
***** SECTION NAME
```
You should print out a new section for the crypto policy check; if you do not, it would be appended to the end of the previous section.

2023-07-25 19:14 UTC, jtakaki-matc commented
@matyasselmeci  Does that change look better?

2023-07-26 19:45 UTC, matyasselmeci approved these changes
One suggestion; pre-approving

2023-07-26 19:45 UTC, matyasselmeci commented on osg-system-profiler
> +    update-crypto-policies --show
```suggestion
    update-crypto-policies --show 2>&1
```
Let's capture stderr if there is any.

2023-07-26 19:48 UTC, jtakaki-matc commented on osg-system-profiler
> +    update-crypto-policies --show
@matyasselmeci gotcha!

2023-07-26 19:51 UTC, merged